### ISSUE TITLE
Teams page 500 error

### ISSUE THREAD

**Issue by markspolakovs** [ystv/public-site#63]
Visit, eg.  https://ystv.co.uk/about/team/computing/ and you get a 500.

Minified stack trace from server logs:

```


  |   | 2023-07-10 22:21:35.750 | TypeError: Cannot read properties of undefined (reading 'name') |  
  |   | 2023-07-10 22:21:35.750 | at TeamID (/app/.next/server/pages/about/team/[name].js:71:32) |  
  |   | 2023-07-10 22:21:35.750 | at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44) |  
  |   | 2023-07-10 22:21:35.750 | at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253) |  
  |   | 2023-07-10 22:21:35.750 | at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89) |  
  |   | 2023-07-10 22:21:35.750 | at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98) |  
  |   | 2023-07-10 22:21:35.751 | at bd (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404) |  
  |   | 2023-07-10 22:21:35.751 | at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217) |  
  |   | 2023-07-10 22:21:35.751 | at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98) |  
  |   | 2023-07-10 22:21:35.751 | at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145) |  
  |   | 2023-07-10 22:21:35.751 | at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)


```

**Comment by thekingofjibs** [comment]
fixed by 89240531bbea6e4829096264c8791d9ab0a82d12
